### ISSUE TITLE
subir csv modificado

### ISSUE THREAD

**Issue by aleoncavallo** [adalessandro/EdP-2023-TP-Final#1]

**Comment by adalessandro** [comment]
El csv ya está subido modificado acá en este repo. Vos decís de subirlo a otro lado?

**Comment by adalessandro** [comment]
Acá lo actualicé https://github.com/adalessandro/EdP-2023-TP-Final/commit/20af22557b7ef475d9448d8c07592ceead2677ff

**Comment by adalessandro** [comment]
Y su url https://github.com/adalessandro/EdP-2023-TP-Final/commit/6fa84ba397909f1c06b22556c939c58515b31edc en el enunciado, apuntando a este repo
