### ISSUE TITLE
images link is broken, replace with https://thispersondoesnotexist.com/ 

### ISSUE THREAD

**Issue by aleoncavallo** [adalessandro/EdP-2023-TP-Final#7]

**Comment by adalessandro** [comment]
Podés proponer la URL con la que habría que reemplazar la existente?

**Comment by adalessandro** [comment]
El comando de imagemagick que se sugiere en el tp, sigue funcionando?

**Comment by aleoncavallo** [comment]
ahí lo probé, anda
la url es: https://thispersondoesnotexist.com/

**Comment by adalessandro** [comment]
Fixed en https://github.com/adalessandro/EdP-2023-TP-Final/commit/539dd4f637688b2a776e3b269fd3bdd729fd533e
